#! /usr/bin/perl
# nagios: -epn

# Nagios plugin to check Puppet dashboard for failing, unresponsive or
# unreported agents

# anders@fupp.net, 2015-06-18

use LWP::UserAgent;
use Data::Dumper;
use HTML::TableExtract;
use Getopt::Std;
use HTTP::Request::Common qw(GET);

getopts('du:l:p:');

sub errexit {
	my $rc = shift;
	my $txt = shift;
	print "$txt\n";
	exit($rc);
}

errexit(2,"Usage: check_puppet_dashboard -u <url> [-l <user> -p <password>]") unless ($opt_u);

my $ua = LWP::UserAgent->new;
$te = HTML::TableExtract->new;

my $req = GET $opt_u;
if ($opt_l && $opt_p) {
	$req->authorization_basic($opt_l,$opt_p);
}
my $res = $ua->request($req);


errexit(2,"Could not fetch a good response from $opt_u, " . $res->status_line) unless ($res->is_success);
$te->parse($res->content);
%values = ();

$ts = ($te->tables)[0];
foreach $row ($ts->rows) {
	if (join("", @$row) =~ /\s*(\d+)\s+(\w+)/) {
		$key = lc($2);
		$values{"$key"} = $1;
	}
}

$txt = $values{"failed"}. " failing nodes, " . $values{"unresponsive"} . " unresponsive, " . $values{"unreported"} . " unreported.";
if ($values{"failed"} > 0) {
	$ret = 2;
} elsif ($values{"unresponsive"} > 0 || $values{"unreported"} > 0) {
	$ret = 1;
} else {
	$ret = 0;
}
errexit($ret,$txt);
